/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import paint.controller.Controller;

public class View extends javax.swing.JFrame {

    public View() {
        this.controller = Controller.getInstance();
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    
    /**
     * @return the borderColorButton
     */
    public javax.swing.JButton getBorderColorButton() {
        return borderColorButton;
    }

    public JToggleButton getResizeButton() {
        return resizeButton;
    }

    /**
     * @param borderColorButton the borderColorButton to set
     */
    public void setBorderColorButton(javax.swing.JButton borderColorButton) {
        this.borderColorButton = borderColorButton;
    }

    public JToggleButton getTriangleButton() {
        return triangleButton;
    }

    public JButton getRemoveButton() {
        return removeButton;
    }

    public JButton getCloneButton() {
        return cloneButton;
    }


    

    /**
     * @return the circleButton
     */
    public javax.swing.JToggleButton getCircleButton() {
        return circleButton;
    }

    /**
     * @param circleButton the circleButton to set
     */
    public void setCircleButton(javax.swing.JToggleButton circleButton) {
        this.circleButton = circleButton;
    }

    /**
     * @return the fillColorButton
     */
    public javax.swing.JButton getFillColorButton() {
        return fillColorButton;
    }

    /**
     * @param fillColorButton the fillColorButton to set
     */
    public void setFillColorButton(javax.swing.JButton fillColorButton) {
        this.fillColorButton = fillColorButton;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @param paintPanel2 the paintPanel2 to set
     */
    public void setPaintPanel2(javax.swing.JPanel paintPanel2) {
        this.paintPanel2 = paintPanel2;
    }

    /**
     * @return the rectangleButton
     */
    public javax.swing.JToggleButton getRectangleButton() {
        return rectangleButton;
    }

    /**
     * @param rectangleButton the rectangleButton to set
     */
    public void setRectangleButton(javax.swing.JToggleButton rectangleButton) {
        this.rectangleButton = rectangleButton;
    }

    /**
     * @param redoButton the redoButton to set
     */
    public void setRedoButton(javax.swing.JButton redoButton) {
        this.redoButton = redoButton;
    }

    /**
     * @param undoButton the undoButton to set
     */
    public void setUndoButton(javax.swing.JButton undoButton) {
        this.undoButton = undoButton;
    }
    
    public JButton getRedoButton() {
        return redoButton;
    }

    public JButton getUndoButton() {
        return undoButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapesButtonsGroup = new javax.swing.ButtonGroup();
        paintPanel2 = new PaintPanel();
        jPanel1 = new javax.swing.JPanel();
        rectangleButton = new javax.swing.JToggleButton();
        circleButton = new javax.swing.JToggleButton();
        squareButton = new javax.swing.JToggleButton();
        elipseButton = new javax.swing.JToggleButton();
        lineButton = new javax.swing.JToggleButton();
        triangleButton = new javax.swing.JToggleButton();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        borderColorButton = new javax.swing.JButton();
        fillColorButton = new javax.swing.JButton();
        fillToggleButton = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jsonLoadButton = new javax.swing.JButton();
        xmlLoadButton = new javax.swing.JButton();
        xmlSaveButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        selectButton = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        removeButton = new javax.swing.JButton();
        cloneButton = new javax.swing.JButton();
        resizeButton = new javax.swing.JToggleButton();
        jsonSaveButton = new javax.swing.JButton();

        shapesButtonsGroup.add(circleButton);
        shapesButtonsGroup.add(rectangleButton);
        shapesButtonsGroup.add(squareButton);
        shapesButtonsGroup.add(elipseButton);
        shapesButtonsGroup.add(lineButton);
        shapesButtonsGroup.add(triangleButton);
        rectangleButton.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        paintPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ((PaintPanel)paintPanel2).setController(controller);

        javax.swing.GroupLayout paintPanel2Layout = new javax.swing.GroupLayout(paintPanel2);
        paintPanel2.setLayout(paintPanel2Layout);
        paintPanel2Layout.setHorizontalGroup(
            paintPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paintPanel2Layout.setVerticalGroup(
            paintPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rectangleButton.setText("Rectangle");
        rectangleButton.setActionCommand("rectangle");

        circleButton.setText("Circle");
        circleButton.setActionCommand("circle");

        squareButton.setText("Square");
        squareButton.setActionCommand("square");

        elipseButton.setText("Ellipse");
        elipseButton.setActionCommand("ellipse");

        lineButton.setText("Line");
        lineButton.setActionCommand("line");

        triangleButton.setText("Triangle");
        triangleButton.setActionCommand("triangle");

        undoButton.setText("Undo");

        redoButton.setText("Redo");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rectangleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(squareButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elipseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(triangleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rectangleButton)
                            .addComponent(circleButton)
                            .addComponent(squareButton)
                            .addComponent(elipseButton)
                            .addComponent(lineButton)
                            .addComponent(triangleButton)
                            .addComponent(undoButton)
                            .addComponent(redoButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        borderColorButton.setText("");
        borderColorButton.setToolTipText("Border color");
        borderColorButton.setBackground(controller.getBorderColor());
        borderColorButton.setPreferredSize(new Dimension(30 , 30));

        fillColorButton.setText("");
        fillColorButton.setToolTipText("Fill color");
        fillColorButton.setBackground(controller.getFillColor());
        fillColorButton.setPreferredSize(new Dimension(30 , 30));

        fillToggleButton.setText("Fill");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(borderColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fillToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borderColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fillToggleButton)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jsonLoadButton.setText("JSON Load");

        xmlLoadButton.setText("XML Load");

        xmlSaveButton.setText("XML Save");

        selectButton.setText("Select");
        selectButton.setToolTipText("Select a shape");
        shapesButtonsGroup.add(selectButton);
        selectButton.setActionCommand("Select");

        removeButton.setText("Remove");

        cloneButton.setText("Copy");

        resizeButton.setText("Resize");

        jsonSaveButton.setText("JSON Save");
        jsonSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsonSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jsonSaveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jsonLoadButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cloneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xmlSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xmlLoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(selectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cloneButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xmlSaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xmlLoadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsonLoadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsonSaveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paintPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paintPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 284, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsonSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsonSaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsonSaveButtonActionPerformed

    public JToggleButton getLineButton() {
        return lineButton;
    }

    public JToggleButton getElipseButton() {
        return elipseButton;
    }

    public JToggleButton getSquareButton() {
        return squareButton;
    }
/*
    */

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }}
                      
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColorButton;
    private javax.swing.JToggleButton circleButton;
    private javax.swing.JButton cloneButton;
    private javax.swing.JToggleButton elipseButton;
    private javax.swing.JButton fillColorButton;
    private javax.swing.JToggleButton fillToggleButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jsonLoadButton;
    private javax.swing.JButton jsonSaveButton;
    private javax.swing.JToggleButton lineButton;
    private javax.swing.JPanel paintPanel2;
    private javax.swing.JToggleButton rectangleButton;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JToggleButton resizeButton;
    private javax.swing.JToggleButton selectButton;
    private javax.swing.ButtonGroup shapesButtonsGroup;
    private javax.swing.JToggleButton squareButton;
    private javax.swing.JToggleButton triangleButton;
    private javax.swing.JButton undoButton;
    private javax.swing.JButton xmlLoadButton;
    private javax.swing.JButton xmlSaveButton;
    // End of variables declaration//GEN-END:variables
    private Controller controller;
    
    public PaintPanel getPaintPanel2() {
        return (PaintPanel) paintPanel2;
    }

    public void setPaintPanel2(paint.View.PaintPanel paintPanel2) {
        this.setPaintPanel2(paintPanel2);
    }

    public javax.swing.JToggleButton getSelectButton() {
        return selectButton;
    }

    public void setSelectButton(javax.swing.JToggleButton selectButton) {
        this.selectButton = selectButton;
    }

    public javax.swing.ButtonGroup getShapesButtonsGroup() {
        return shapesButtonsGroup;
    }

    public void setShapesButtonsGroup(javax.swing.ButtonGroup shapesButtonsGroup) {
        this.shapesButtonsGroup = shapesButtonsGroup;
    }

    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public JToggleButton getFillToggleButton() {
        return fillToggleButton;
    }
    
    public javax.swing.JButton getJsonLoadButton() {
        return jsonLoadButton;
    }

    public void setJsonLoadButton(javax.swing.JButton jsonLoadButton) {
        this.jsonLoadButton = jsonLoadButton;
    }

    public javax.swing.JButton getJsonSaveButton() {
        return jsonSaveButton;
    }

    public void setJsonSaveButton(javax.swing.JButton jsonSaveButton) {
        this.jsonSaveButton = jsonSaveButton;
    }

    public javax.swing.JButton getXmlLoadButton() {
        return xmlLoadButton;
    }

    public void setXmlLoadButton(javax.swing.JButton xmlLoadButton) {
        this.xmlLoadButton = xmlLoadButton;
    }

    public javax.swing.JButton getXmlSaveButton() {
        return xmlSaveButton;
    }

    public void setXmlSaveButton(javax.swing.JButton xmlSaveButton) {
        this.xmlSaveButton = xmlSaveButton;
    }

}
